---
version: '3'
services:
    tomcat_build:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - webdata:/usr/local/tomcat/webapps/

    tomcat_deploy:
        image: tomcat:alpine
        ports:
            - '80:8080'
        volumes:
            - webdata:/usr/local/tomcat/webapps/
        depends_on:
            - tomcat_build

volumes:
    webdata:




