- name: upgrade package
  apt:
    update_cache: true
    upgrade: true

- name: rsync install
  apt: name=rsync state=present

- name: equipments install
  apt: name={{item}} state=present
  with_items:
    - maven
    - git
  when: state=='First'

- name: equipments install
  apt: name=openjdk-11-jdk state=present
  when: state=='Second'