- name: create tomcat directory
  file:
    path: {{ dest_folder }}
    state: directory
    mode: 0755

- name: download & unarchive
  unarchive:
    src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.96/bin/apache-tomcat-9.0.96.tar.gz
    dest: {{ dest_folder }}
    remote_src: yes
    extra_opts: [--strip-components=1]
  notify: tomcat start

- name: synchronize src to dst
  hosts: db
  command: rsync -avz {{ src_folder }}/target/hello-world-war-1.0.0.war\
           'ssh -i /root/.ssh/link' root@{{hosts}}:{{ dest_folder }}/webapps